services:
    postgres:
        image: postgres:15
        container_name: geo_postgres
        restart: always
        env_file:
            - ../config/.env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - pg_data:/var/lib/postgresql/data

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - "6379:6379"

    airflow-init:
        image: apache/airflow:2.8.1
        container_name: airflow_init
        depends_on:
            - postgres
            - redis
        env_file:
            - ../config/.env
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
            - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
            - AIRFLOW__CORE__LOAD_EXAMPLES=False
        entrypoint: /bin/bash
        command:
            - -c
            - |
                airflow db init
        volumes:
            - ../dags:/opt/airflow/dags
            - ../src:/opt/airflow/src
            - ../config:/opt/airflow/config
            - /Users/mahamadoucamara/Desktop/personal_project/geolocation_ip_app/data:/opt/airflow/data
            - airflow_logs:/opt/airflow/logs
            - airflow_plugins:/opt/airflow/plugins

    airflow-webserver:
        image: apache/airflow:2.8.1
        container_name: airflow_webserver
        restart: always
        depends_on:
            - airflow-init
        ports:
            - "8080:8080"
        env_file:
            - ../config/.env
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
            - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
            - AIRFLOW__CORE__LOAD_EXAMPLES=False
            - AIRFLOW__WEBSERVER__RBAC=True
        command: webserver
        volumes:
            - ../dags:/opt/airflow/dags
            - ../src:/opt/airflow/src
            - ../config:/opt/airflow/config
            - /Users/mahamadoucamara/Desktop/personal_project/geolocation_ip_app/data:/opt/airflow/data
            - airflow_logs:/opt/airflow/logs
            - airflow_plugins:/opt/airflow/plugins

    airflow-scheduler:
        image: apache/airflow:2.8.1
        container_name: airflow_scheduler
        restart: always
        depends_on:
            - airflow-webserver
        env_file:
            - ../config/.env
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
            - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
        command: scheduler
        volumes:
            - ../dags:/opt/airflow/dags
            - ../src:/opt/airflow/src
            - ../config:/opt/airflow/config
            - /Users/mahamadoucamara/Desktop/personal_project/geolocation_ip_app/data:/opt/airflow/data
            - airflow_logs:/opt/airflow/logs
            - airflow_plugins:/opt/airflow/plugins

    airflow-worker:
        image: apache/airflow:2.8.1
        container_name: airflow_worker
        restart: always
        depends_on:
            - redis
            - postgres
        env_file:
            - ../config/.env
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
            - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
            - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
        command: celery worker
        volumes:
            - ../dags:/opt/airflow/dags
            - ../src:/opt/airflow/src
            - ../config:/opt/airflow/config
            - /Users/mahamadoucamara/Desktop/personal_project/geolocation_ip_app/data:/opt/airflow/data
            - airflow_logs:/opt/airflow/logs
            - airflow_plugins:/opt/airflow/plugins

volumes:
    pg_data:
    airflow_logs:
    airflow_plugins:
